sudo: required
dist: trusty
language: cpp
notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - libgtest-dev
    - build-essential
    - cmake
install: 
  - cmake .
  - make VERBOSE=1
script: 
  - ./unittests
